fps: 5
detector_ids:
  counting: "det_"
image_sources:
  - id:
      serial_number: abc123
    input_type: generic_usb
    options:
      resolution:
        width: 1902 # 3840
        height: 1080 # 2160
      is_video: true # necessary to keep the frame rate high, depends on https://github.com/groundlight/framegrab/tree/tim/buffer
      num_90_deg_rotations: 2
