detector_ids:
  object_detection: 
    - "det_"
    - "det_"
image_sources:
  - id:
      serial_number: 123456
    input_type: generic_usb
    options:
      resolution:
        width: 3840
        height: 2160
      crop:
        relative:
          left: 0.05
          right: 0.9
      is_video: true # necessary to keep the frame rate high
